/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7e3308ae-ed84-442a-ad0e-c200a87a7515",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gmgE0Lo5S",
    "aws_user_pools_web_client_id": "gtqr2mfvcovuscum6afu4fgoj",
    "oauth": {
        "domain": "gifapp682166ff-682166ff-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://5w7ag7meqfbqfeykftlgm5pkyq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
